spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format-sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dvo_db
    username: postgres
    password: postgres
    hikari:
      schema: news_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS news_schema
      connection-timeout: 10000